
#pragma once

#define XYZLABS_VERSION_MAJOR 4
#define XYZLABS_VERSION_MINOR 3
#define XYZLABS_VERSION_PATCH 0

#define XYZLABS_VERSION_STRING "4.3.0"

#define XYZLABS_VERSION_NUMBER ((XYZLABS_VERSION_MAJOR << 16) | (XYZLABS_VERSION_MINOR << 8) | XYZLABS_VERSION_PATCH)
